language: node_js

addons:
  apt:
    packages:
      - xvfb

node_js:
  - "4"
  - "5"
  - "6"
  - "10"

notifications:
  email: false

install:
  - npm i
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &